import graphene
from graphql import GraphQLError
from sqlalchemy import desc
from graphene_sqlalchemy import (SQLAlchemyObjectType)

from api.office.models import Office as OfficeModel
from helpers.auth.error_handler import SaveContextManager
from utilities.validations import validate_entity_types

# decorators
from helpers.auth.auth import Authentication


class Office(SQLAlchemyObjectType):
    """
        Autogenerated return type of a office
    """
    class Meta:
        model = OfficeModel


class CreateOffice(graphene.Mutation):
    """
        Mutation to create a party
    """
    class Arguments:
        office_name = graphene.String(required=True)
        age_limit = graphene.Int(required=True)
        office_type = graphene.String()
        description = graphene.String(required=True)
        status = graphene.String()

    office = graphene.Field(Office)

    @Authentication.login_required
    @Authentication.user_roles(['admin'])
    def mutate(self, info, **kwargs):
        validate_entity_types(['state', 'legislative', 'federal', 'local_govenment'], 'office_type', **kwargs)  # noqa
        office = OfficeModel(**kwargs)

        payload = {
            'model': OfficeModel,
            'field': 'office_name',
            'value': kwargs['office_name']
        }
        with SaveContextManager(office, 'Office name', payload):
            return CreateOffice(office=office)


class allOffices(graphene.ObjectType):
    """
        Get all offices
    """
    offices = graphene.List(Office)


class SingleOffice(graphene.ObjectType):
    office = graphene.Field(Office)


class Query(graphene.ObjectType):
    all_offices = graphene.List(
        Office,
        limit=graphene.Int(),
        offset=graphene.Int(),
        description="Returns a list of all offices \
        \n- limit: Limit number of offices to return\
        \n- offset: Number of offices to skip")

    single_office = graphene.Field(
        SingleOffice,
        office_id=graphene.Int(),
        description="Returns an office details and accepts argument\
            \n- office_id: A unique identifier of the office"
    )

    @Authentication.login_required
    def resolve_all_offices(self, info, **kwargs):
        # get all officed
        limit = kwargs.get('limit') or 10
        offset = kwargs.get('offset') or 0
        query = Office.get_query(info)
        offices = query.order_by(
            desc(OfficeModel.created_at)).offset(offset).limit(limit)
        return offices

    @Authentication.login_required
    def resolve_single_office(self, info, office_id):
        query = Office.get_query(info)
        office = query.filter(OfficeModel.id == office_id).first()
        if not office:
            raise GraphQLError("office not found")

        return SingleOffice(office=office)


class Mutation(graphene.ObjectType):
    """
        Mutation to create an office
    """
    create_office = CreateOffice.Field(
        description="Creates a new political office with arguments\
            \n- office_name: The name of the political office[required]\
            \n- age_limit: The minimum age_limit for an office[required]\
            \n- office_type: type of office like state, federal[required]\
            \n- status: The status field of an office,(new, updated) [required]\
        "
    )
