import graphene
from graphene_sqlalchemy import (SQLAlchemyObjectType)
from graphql import GraphQLError

from api.user.models import User as UserModel
from utilities.validations import verify_email
from helpers.auth.error_handler import SaveContextManager

# decorators
from helpers.auth.auth import Authentication


class User(SQLAlchemyObjectType):
    """
        Autogenerated return type of a user
    """
    class Meta:
        model = UserModel


class CreateUser(graphene.Mutation):
    """
        Mutation to create a user
    """
    class Arguments:
        first_name = graphene.String(required=True)
        last_name = graphene.String(required=True)
        other_names = graphene.String()
        email = graphene.String(required=True)
        password = graphene.String(required=True)
        picture = graphene.String()
        user_type = graphene.String()

    token = graphene.String()
    user = graphene.Field(User)

    def mutate(self, info, **kwargs):
        user = UserModel(**kwargs)

        if not verify_email(user.email):
            raise GraphQLError("This email is not allowed")
        payload = {
            'model': UserModel, 'field': 'email', 'value':  kwargs['email']
        }
        with SaveContextManager(user, 'User email', payload):
            token = user.generate_token()
            return CreateUser(user=user, token=token)


class allUsers(graphene.ObjectType):
    """
        all users
    """
    users = graphene.List(User)


class Query(graphene.ObjectType):
    """
        Query to get list of all users
    """
    all_users = graphene.List(
        User,
        description="Returns a list of all users")

    """
        Query to get a particular user
    """
    login_user = graphene.Field(
        User,
        user_email=graphene.String(),
        user_password=graphene.String(),
        description="Returns a particular user and accepts the arguments\
            \n- user_email: The email address of the user trying to login\
            [required]\
            \n- user_password: The password for the user trying to login\
            [required]")

    @Authentication.login_required
    def resolve_all_users(self, info):
        # get all users
        query = User.get_query(info)
        return query

    def resolve_login_user(self, info, user_email, user_password):
        query = User.get_query(info)
        user = query.filter(UserModel.email == user_email).first()

        if not user:
            raise GraphQLError("User not found")

        verify_user = Authentication.verify_password(
            user_password, user.password
        )

        if not verify_user:
            raise GraphQLError("Incorrect credentials supplied")

        return user


class Mutation(graphene.ObjectType):
    """
        Mutation to create user
    """
    create_user = CreateUser.Field(
        description="Creates a new user with the arguments\
            \n- first_name: The first_name field of the user[required]\
            \n- last_name: The last_name field of the user[required]\
            \n- other_names: The other_names field of the user\
            \n- email: The email field of the user[required]\
            \n- password: The password field of the user[required]\
            \n- user_type: The type field of a user[required]\
            \n- picture: The picture field of a user")
